## Python NumPy Exercise

In [3]:
import numpy as np

### Question 1: Create a 4X2 integer array and Prints its attributes

Note: The element must be a type of unsigned int16. And print the following Attributes: –

The shape of an array.  
Array dimensions.  
The Length of each element of the array in bytes.

In [36]:
firstarray = np.empty([4,2], dtype=np.uint16)

In [37]:
print(firstarray)

[[53328 36505]
 [  589     0]
 [    0     0]
 [    0     0]]


In [39]:
np.empty([4,2], dtype=np.uint8)

array([[112,   0],
       [ 92,   0],
       [ 77,   0],
       [121,   0]], dtype=uint8)

In [40]:
firstarray.shape # outputs the shape of the array

(4, 2)

In [41]:
firstarray.ndim # Outputs the dimensions of the array

2

In [42]:
firstarray.itemsize # Length of each element of array in bytes

2

### Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [47]:
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

### Question 3: Following is the provided numPy array. return array of items in the third column from all rows

In [11]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [12]:
sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [13]:
sampleArray[2,2]

99

In [14]:
sampleArray[:,:]

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [58]:
sampleArray[:,2]

array([33, 66, 99])

In [20]:
sampleArray[...,2]

array([33, 66, 99])

### Question 4: Following is the given numpy array return array of odd rows and even columns

In [28]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [29]:
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [42]:
sampleArray[0::1]

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [51]:
sampleArray[1::2]       # sample[rows, columns]

array([[15, 18, 21, 24],
       [39, 42, 45, 48]])

In [44]:
sampleArray[:,0::1]

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [54]:
sampleArray[:,1::2] # Array for even COLUMNS - 2 and 4

array([[ 6, 12],
       [18, 24],
       [30, 36],
       [42, 48],
       [54, 60]])

In [52]:
sampleArray[0::2,:] # Array of odd ROWS - 1, 3 and 5

array([[15, 18, 21, 24],
       [39, 42, 45, 48]])

In [50]:
sampleArray[0::2, 1::2] # Array of odd rows and even columns

array([[ 6, 12],
       [30, 36],
       [54, 60]])

### Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square of each element

In [3]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [71]:
result_array = arrayOne + arrayTwo # Adding the elements of the two arrays

In [5]:
result_array

array([[20, 39, 33],
       [25, 25, 28]])

In [68]:
print(result_array)

[[20 39 33]
 [25 25 28]]


In [6]:
result_array^2

array([[22, 37, 35],
       [27, 27, 30]], dtype=int32)

In [7]:
result_array.sum()   # Sum of all elements in the array

170

In [70]:
np.sqrt(result_array).round(1)  # Square root of each element of the array

array([[4.5, 6.2, 5.7],
       [5. , 5. , 5.3]])

In [67]:
np.square(result_array) # Square of each element of the result array

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

### Question 6: Split the array into four equal-sized sub-arrays

Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [21]:
new_arr = np.arange(10,34,1).reshape(8,3)

In [22]:
new_arr

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [24]:
sub_arr = np.split(new_arr, 4)

In [25]:
sub_arr

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

### Question 7; Sort following NumPy array

7.1- by the second row and  
7.2- by the second column

In [4]:
sampleArray7 = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [5]:
sampleArray7

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [6]:
np.sort(sampleArray7)

array([[34, 43, 73],
       [12, 22, 82],
       [53, 66, 94]])

In [7]:
sampleArray7[1,:]

array([82, 22, 12])

In [8]:
sampleArray7[1,:].argsort()

array([2, 1, 0], dtype=int64)

In [11]:
sampleArray7[:,sampleArray7[1,:].argsort()]

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [72]:
sampleArray7[sampleArray7[1,:].argsort()]  # Sorting original array by second column

array([[53, 94, 66],
       [82, 22, 12],
       [34, 43, 73]])

In [74]:
sampleArray7[:,sampleArray7[1,:].argsort()]  # Sorting original array by second row

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [20]:
sampleArray7[np.argsort(sampleArray7[1,:])]   # Sorting original array by rows

array([[53, 94, 66],
       [82, 22, 12],
       [34, 43, 73]])

In [21]:
sampleArray7[np.argsort(sampleArray7[:,1])]   # Sorting original array by rows

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

In [19]:
sampleArray7

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [84]:
np.argsort(sampleArray7[:,1])  # Sorted index of rows based on second column

array([1, 0, 2], dtype=int64)

In [88]:
sampleArray7.sort

In [90]:
np.sort

<function numpy.sort(a, axis=-1, kind=None, order=None)>

### Question 8: Following is the 2-D array. Print max from axis 0 and min from axis 1

In [22]:
sampleArray8 = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

In [23]:
sampleArray8

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [24]:
np.amin(sampleArray8)

12

In [25]:
np.min(sampleArray8)

12

In [26]:
np.amin(sampleArray8,1)

array([34, 12, 53])

In [30]:
np.min(sampleArray8,1)

array([34, 12, 53])

In [31]:
np.max(sampleArray8,1)

array([73, 82, 94])

In [32]:
np.max(sampleArray8)

94

### Question 9: Following is the input NumPy array delete column two and insert following new column in its place.

In [34]:
sampleArray9 = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = np.array([[10,10,10]])

In [35]:
sampleArray9

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [36]:
newsample9 = np.delete(sampleArray9, 1, axis=1)

In [37]:
newsample9

array([[34, 73],
       [82, 12],
       [53, 66]])

In [56]:
newsample = np.insert(newsample9,1,10, axis=1) # Axis 1 stands for columns while 0 stands for rows

In [57]:
newsample

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])